### PR TITLE
[BUGFIX] [issue-18] Solved Duplicate Active Quotes after using Login …

### LINKED ISSUE #18: Duplicate Active Quotes
When you use the login as customer functionality for an existing customer which already has a filled quote then a new quote will be create. 

Because of this situation it is possible that a customer has multiple active quotes and when the customer submits the new quote and places an order the original quote will be activated. Now the customer has random old products in his shopping cart form his own original quote

See the screenshot of the quote table with 3 active quotes

image

### PR DESCRIPTION
**Pull request by lewisvoncken**
…As Customer functionality

this pull request will resolve #18 

The loadCustomerQuote function is based on the Default Magento Observer loadCustomerQuote which observers event customer_login

### CODE REVIEW

**Comment by southerncomputer** [comment]
$this->_checkoutSession->loadCustomerQuote();

I think you forget to declared protected $_checkoutSession;

**Comment by lewisvoncken** [comment]
@southerncomputer I have just declared the variable

**Comment by magefan** [comment]
Thank you @lewisvoncken for the contribution! :+1:

**Comment by lewisvoncken** [comment]
@magefan no problem, thanks for the module! Could you please add a tag so there is a new package?

**Comment by magefan** [comment]
@lewisvoncken - done

**Pull request merged**
